version: '1'
services:
  server:
    image: ${CI_REGISTRY_IMAGE}:${CI_IMAGE_TAG}
    environment:
      - DB_URL=${DB_URL}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_EXPIRATION_HOURS=${JWT_EXPIRATION_HOURS}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    restart: always
    network_mode: "host"
